[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "never"

[phases.setup]
nixPkgs = ["python39"]

[phases.build]
cmds = [
    "cd backend",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
] 