[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100 