[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
restartPolicyType = "never"

[phases.setup]
nixPkgs = ["python39"]

[phases.build]
cmds = [
    "cd backend",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
] 