"""add vehicle expiration and status fields

Revision ID: 2dd4bc9eb399
Revises: a684f898b4c2
Create Date: 2025-06-21 11:31:27.301540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd4bc9eb399'
down_revision: Union[str, None] = 'a684f898b4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('soat_vencimiento', sa.Date(), nullable=True))
    op.add_column('vehiculos', sa.Column('tecnomecanica_vencimiento', sa.Date(), nullable=True))
    op.add_column('vehiculos', sa.Column('kit_vencimiento', sa.Date(), nullable=True))
    op.add_column('vehiculos', sa.Column('pico_placa', sa.String(), nullable=True))
    op.add_column('vehiculos', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'activo')
    op.drop_column('vehiculos', 'pico_placa')
    op.drop_column('vehiculos', 'kit_vencimiento')
    op.drop_column('vehiculos', 'tecnomecanica_vencimiento')
    op.drop_column('vehiculos', 'soat_vencimiento')
    # ### end Alembic commands ###
