"""add pico y placa config table

Revision ID: 6ba28baaa02f
Revises: 2dd4bc9eb399
Create Date: 2025-06-21 11:44:30.630756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba28baaa02f'
down_revision: Union[str, None] = '2dd4bc9eb399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pico_y_placa_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pico_y_placa_config_id'), 'pico_y_placa_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pico_y_placa_config_id'), table_name='pico_y_placa_config')
    op.drop_table('pico_y_placa_config')
    # ### end Alembic commands ###
