"""add_novedades_table

Revision ID: 6e48131e23c5
Revises: e55f2a2af79c
Create Date: 2025-06-19 20:11:53.165686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e48131e23c5'
down_revision: Union[str, None] = 'e55f2a2af79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trayecto_id', sa.Integer(), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ACCIDENTE', 'AVERIA_MECANICA', 'TRAFICO', 'PROBLEMA_RUTA', 'OTRO', name='tiponovedad'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['trayecto_id'], ['trayectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novedades_id'), 'novedades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novedades_id'), table_name='novedades')
    op.drop_table('novedades')
    # ### end Alembic commands ###
