"""add distancia, tiempo_estimado y activa to rutas

Revision ID: a684f898b4c2
Revises: 6e48131e23c5
Create Date: 2025-06-20 15:00:31.025451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684f898b4c2'
down_revision: Union[str, None] = '6e48131e23c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rutas', sa.Column('distancia', sa.Float(), nullable=True))
    op.add_column('rutas', sa.Column('tiempo_estimado', sa.Integer(), nullable=True))
    op.add_column('rutas', sa.Column('activa', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas', 'activa')
    op.drop_column('rutas', 'tiempo_estimado')
    op.drop_column('rutas', 'distancia')
    # ### end Alembic commands ###
